[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GASTON"
version = "0.0.1"
authors = [
  { name="Uthsav Chitra", email="uchitra@princeton.edu" },
  { name="Brian Arnold", email="brianjohnarnold@gmail.com" },
  { name="Hirak Sarkar", email="hirak@princeton.edu" },
  { name="Cong Ma", email="congma@princeton.edu" },
  { name="Ben Raphael", email="braphael@cs.princeton.edu" },
]
description = "GASTON: interpretable deep learning model for spatial transcriptomics"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch",
    "matplotlib",
    "pandas",
    "scikit-learn",
    "numpy",
    "jupyterlab",
    "seaborn",
    "tqdm",
    "scipy"
]

[project.scripts]
gaston = "gaston.__main__:main"

[project.urls]
"Homepage" = "https://github.com/raphael-group/GASTON"

[tool.setuptools.packages.find]
where = ["src"]
include = ["gaston*"]